# general format
format = '$shell$all'

# don't print a new line at the start of the prompt
add_newline = false

# prompt character
[character]     
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

[shell]
zsh_indicator = '\[Z\]'
bash_indicator = '\[\$\]'
powershell_indicator = '\[ï‘ _\]'
unknown_indicator = '\[?\]'
style = 'bold yellow'
disabled = false

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 100
style = 'bold red'
